import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { useEffect, useRef, useState } from 'react'
import axios from 'axios'
import { useRouter } from 'next/router'

export default function WeatherPage() {

    const router = useRouter();

    //dynamically get location from query string
    const location = router.query.location || "Vancouver";
    console.log(location);

    const apiKey = process.env.NEXT_PUBLIC_OPENWEATHERMAP_API_KEY;
    const units = "metric";

    const url = `https://api.openweathermap.org/data/2.5/forecast?q=${location}&units=${units}&appid=${apiKey}`;

    const [data, setData] = useState();
    
    const [dailyData, setDailyData] = useState();
    const grabWeather = useRef(false);

    useEffect(() => {
        const fetchData = async () => {
          try {
            const result = await axios(url);
            console.log(result);
            setData(result.data.list);
          } catch (error) {
            console.log(error);
          }
        };
        if (grabWeather.current) {
          fetchData();
          grabWeather.current = false;
        }
    }, [url]);

    console.log(data);

    useEffect(() => {
        if (data) {
          const dailyData = data.list.reduce((acc, curr) => {
            const date = curr.dt_txt.split(" ")[0];
            if (!acc[date] || acc[date].dt_txt.split(" ")[1] === "21:00:00") {
              acc[date] = curr;
            }
            return acc;
          }, {});
          setDailyData(Object.values(dailyData));
        }
    }, [data]);

    return (
        <>
            <Head>
                <title>Weather</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
            {dailyData ? (
        dailyData.map((item) => (
          <div key={item.dt}>
            <h2>{item.dt_txt}</h2>
            <p>Temperature: {item.main.temp}</p>
            <p>Description: {item.weather[0].description}</p>
            <img
              src={`http://openweathermap.org/img/w/${item.weather[0].icon}.png`}
              alt={item.weather[0].description}
            />
          </div>
        ))
      ) : (
        <p>Loading...</p>
      )}
            </main>
        </>
    )

}
